# WM IoT SDK Device Table
# table_name = "default"

[[dev]]
dev_name = "rcc"
reg_base = 0x40000E00
init_cfg = {init_level = "app", init_priority = 0}
rcc_cfg = [{type = "cpu",  clock = 240},
           {type = "wlan", clock = 160}] #MHz

[[dev]]
dev_name = "dma"
reg_base = 0x40000800
init_cfg = {init_level = "app", init_priority = 0}
irq_cfg = {irq_num = 4, irq_priority = 0}

[[dev]]
dev_name = "gpio"
init_cfg = {init_level = "app", init_priority = 0}
gpio_cfg = [{pin =  0, fun = "fun5", dir = "input",  pupd = "float",    interrupt_mode = "falling_edge"}, #key-sw1
            {pin = 32, fun = "fun5", dir = "input",  pupd = "float",    interrupt_mode = "rising_edge"},  #key-sw2
            {pin = 34, fun = "fun5", dir = "input",  pupd = "float",    interrupt_mode = "double_edge"},  #key-sw3
            {pin = 37, fun = "fun5", dir = "input",  pupd = "float",    interrupt_mode = "low_level"},    #key-sw4
            {pin = 38, fun = "fun5", dir = "input",  pupd = "float",    interrupt_mode = "high_level"},   #key-sw5
            {pin = 40, fun = "fun5", dir = "output", pupd = "pulldown", interrupt_mode = "none"},         #rgb-red
            {pin = 41, fun = "fun5", dir = "output", pupd = "pulldown", interrupt_mode = "none"},         #rgb-green
            {pin = 42, fun = "fun5", dir = "output", pupd = "pulldown", interrupt_mode = "none"},         #rgb-blue
            {pin = 45, fun = "fun5", dir = "output", pupd = "pulldown", interrupt_mode = "none"}]         #beep

[[dev]]
dev_name = "pwm"
reg_base = 0x40011E00
init_cfg = {init_level = "app", init_priority = 0}
irq_cfg = {irq_num = 22, irq_priority = 0}
pin_cfg = [{pin = 40, fun = "fun2"}, #rgb-red
           {pin = 41, fun = "fun2"}, #rgb-green
           {pin = 42, fun = "fun2"}] #rgb-blue
dma_device = "dma"

[[dev]]
dev_name = "uart0"
reg_base = 0x40010600
init_cfg = {init_level = "app", init_priority = 0}
uart_cfg = {baudrate = 115200, parity = "none", stop_bits = 1, data_bits = 8, flow_ctrl = "none"}
irq_cfg = {irq_num = 16, irq_priority = 0}
pin_cfg = [{pin = 35, fun = "fun1"}, #tx
           {pin = 36, fun = "fun1"}] #rx
rcc_device = "rcc"

[[dev]]
dev_name = "iflash"
reg_base = 0x40002000
flash_cfg = {quad_spi = true}
init_cfg = {init_level = "app", init_priority = 0}

[[dev]]
dev_name = "i2c"
reg_base = 0x40010000
init_cfg = {init_level = "app", init_priority = 0}
irq_cfg = {irq_num = 10, irq_priority = 0}
i2c_cfg = {max_clock = 400000, addr_10_bits = false}
pin_cfg = [{pin = 1, fun = "fun2"}, #scl
           {pin = 4, fun = "fun2"}] #sda
rcc_device = "rcc"

[[dev]]
dev_name = "eeprom0"
init_cfg = {init_level = "app", init_priority = 0}
speed_hz          = 400000
size              = 32768
i2c_addr          = 0x50
page_size         = 64
addr_width        = 16
read_only         = false
max_write_time_ms = 5
i2c_device = "i2c"

[[dev]]
dev_name = "pmu"
reg_base = 0x40000D00
init_cfg = {init_level = "app", init_priority = 0}
irq_cfg = {irq_num = 29, irq_priority = 0}
clk_src = "internal"

[[dev]]
dev_name = "adc"
reg_base = 0x40010200
init_cfg = {init_level = "app", init_priority = 0}
irq_cfg = {irq_num = 11, irq_priority = 0}
pin_cfg = [{pin = 3, fun = "fun6"}] #adc channel2
adc_cfg = [{adc_channel = 2, pga_gain1 = "level0", pga_gain2 = "level0", adc_cmp = false}]
dma_device = "dma"

[[dev]]
dev_name = "sdmmc"
reg_base = 0x40000A00
init_cfg = {init_level = "app", init_priority = 0}
irq_cfg = {irq_num = 24, irq_priority = 0}
pin_cfg = [{pin = 22, fun = "fun2"}, #CLK
           {pin = 23, fun = "fun2"}, #CMD
           {pin = 24, fun = "fun2"}, #DAT0
           {pin = 25, fun = "fun2"}, #DAT1
           {pin = 26, fun = "fun2"}, #DAT2
           {pin = 27, fun = "fun2"}] #DAT3
sdh_cfg = {clock_hz = 40000000, bus_width = 1}
dma_device = "dma"
rcc_device = "rcc"

[[dev]]
dev_name = "sdspi"
reg_base = 0x40000A00
init_cfg = {init_level = "app", init_priority = 0}
irq_cfg = {irq_num = 24, irq_priority = 0}
pin_cfg = [{pin =  9, fun = "fun1"}, #CLK
           {pin = 10, fun = "fun1"}] #MOSI
dma_device = "dma"
rcc_device = "rcc"

[[dev]]
dev_name = "nv3041a_spi"
init_cfg = {init_level = "app", init_priority = 0}
spi_cfg = {mode = 0, freq = 60000000, pin_cs = {pin_num = 14, pin_mux = "fun5", dir = "output", pupd = "float"}}
pin_lcd_reset = 7
pin_lcd_dcx = 12
pin_lcd_led = 2
spi_device = "sdspi"
gpio_device = "gpio"

[[dev]]
dev_name = "wdt"
reg_base = 0x40011600
init_cfg = {init_level = "app", init_priority = 0}
irq_cfg = {irq_num = 31, irq_priority = 0}
wdt_cfg = {counter_value = 10000000}

[[dev]]
dev_name = "psram"
reg_base = 0x40002200
init_cfg = {init_level = "app", init_priority = 0}
pin_cfg = [{pin = 16, fun = "fun4"}, #CLK
           {pin = 17, fun = "fun4"}, #CS
           {pin = 18, fun = "fun4"}, #DAT0
           {pin = 19, fun = "fun4"}, #DAT1
           {pin = 20, fun = "fun4"}, #DAT2
           {pin = 21, fun = "fun4"}] #DAT3
psram_cfg = {qspi = true, clock_hz = 80000000}
dma_device = "dma"
rcc_device = "rcc"

[[dev]]
dev_name = "crc"
reg_base = 0x40000600
init_cfg = {init_level = "app", init_priority = 0}
rcc_device = "rcc"

[[dev]]
dev_name = "hash"
reg_base = 0x40000600
init_cfg = {init_level = "app", init_priority = 0}
rcc_device = "rcc"

[[dev]]
dev_name = "rng"
reg_base = 0x40000600
init_cfg = {init_level = "app", init_priority = 0}
rcc_device = "rcc"

[[dev]]
dev_name = "i2s"
reg_base = 0x40012400
init_cfg = {init_level = "app", init_priority = 0}
irq_cfg = {irq_num = 23, irq_priority = 0}
pin_cfg = [{pin = 28, fun = "fun4"}, #BCLK
           {pin = 29, fun = "fun4"}, #LRCLK
           {pin = 33, fun = "fun4"}, #MCLK
           {pin = 30, fun = "fun4"}, #DO
           {pin = 31, fun = "fun4"}] #DI
i2s_cfg = {extal_clock_en = false, mclk_hz = 80000000}
dma_device = "dma"
rcc_device = "rcc"

[[dev]]
dev_name = "es8374"
init_cfg = {init_level = "app", init_priority = 0}
es8374_cfg = {dmic = false, lin1 = false, rin1 = false, lin2 = true, rin2 = true, monoout = true, spkout = true, i2c = true, address = 0x10}
gpio_device = "gpio"
i2s_device = "i2s"
i2c_device = "i2c"
